version: "2.6"

services:
  library_db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./library_back/.env

  library_back:
    depends_on:
      - library_db
    build:
      context: .
      dockerfile: ./library_back/Dockerfile
    command: ["sh", "wait.sh"]
    volumes:
      - ./library_back:/library_back
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env

volumes:
  postgres_db_data: