version: "3.8"

services:
  library_db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./library_back/.env

  library_back:
    depends_on:
      - library_db
    build:
      context: .
      dockerfile: ./library_back/Dockerfile
    command: ["sh", "wait.sh"]
    volumes:
      - ./library_back:/library_back
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env

  library_front:
    build:
      context: .
      dockerfile: library_front/Dockerfile
    volumes:
      - ./library_front:/library_front
    ports:
      - 3000:3000
    depends_on:
      - library_back

volumes:
  db_data: