version: "3.8"

services:
  library_db:
    image: postgres:alpine
    container_name: library_db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./library_back/.env

  library_back:
    depends_on:
      - library_db
    container_name: library_back
    build:
      context: .
      dockerfile: ./library_back/Dockerfile
    volumes:
      - ./library_back:/library_back
    ports:
      - 8000:8000
    env_file:
      - ./library_back/.env

  library_front:
    depends_on:
      - library_back
    container_name: library_front
    build:
      context: .
      dockerfile: library_front/Dockerfile
    volumes:
      - ./library_front:/library_front
    ports:
      - 3000:3000

  web:
    depends_on:
      - library_front
    container_name: web
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    
volumes:
  db_data: